server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /health { proxy_pass http://api:8000; }
    location /architectures { proxy_pass http://api:8000; }
    location /profile { proxy_pass http://api:8000; }
    location /compare { proxy_pass http://api:8000; }
    location /runs/ { proxy_pass http://api:8000; }

    location / {
        try_files $uri /index.html;
    }
}
